name: phylodynamic
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - mafft=7.525
  - iqtree=3.0.1
  - seqkit=2.12.0
  - pip=24.0
  - python-kaleido=0.2.1
  - nextclade=3.18.1
  - pip:
    - phylo-treetime=0.11.4
    - plotly=5.24.1
    - pandas
    - numpy