name: phylodynamic
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - mafft=7.525
  - iqtree=3.0.1
  - seqkit=2.12.0
  - pip=24.0
  - pip:
    - phylo-treetime=0.11.4